### PR TITLE
optmize cli flags for accept callback

### PR DESCRIPTION
**Pull request by buaazp**
And use custom kcp package name for godef.

Details:

If use `cli.Int()` in listener's callback function, it will be invoked after every conn accepted.
While `cli.Int()` calls `set.Lookup()` and `strconv.ParseInt()`, they are heavy and unnecessary.
This PR separate `cli.Int()`, `cli.String()`, `cli.Bool` from conn's callback function, which will improve the performance of server and client.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xtaci/kcptun/pull/97%23issuecomment-238077916%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xtaci/kcptun/pull/97%23issuecomment-238077916%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22much%20clearer%20%21%20thanks.%5Cr%5Cnbut%2C%20import%20renaming%20seems%20to%20be%20not%20so%20necessary.%20%22%2C%20%22created_at%22%3A%20%222016-08-07T11%3A44%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2346725%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/xtaci%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xtaci/kcptun/pull/97#issuecomment-238077916'>General Comment</a></b>
- <a href='https://github.com/xtaci'></a> much clearer ! thanks.
but, import renaming seems to be not so necessary.

<a href='https://www.codereviewhub.com/xtaci/kcptun/pull/97?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xtaci/kcptun/pull/97?approve=1'></a>&nbsp;<a href='https://github.com/xtaci/kcptun/pull/97'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xtaci** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xtaci/kcptun/pull/97'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by xtaci** [comment]
much clearer ! thanks.
but, import renaming seems to be not so necessary.

**Comment by buaazp** [comment]
It's just for the `godef` plugin to jump to the right definition position(in vim or sublime text).
Because the import path `kcp-go` is not match your package name `kcp`.
You can change it by yourself.
^_^

**Comment by xtaci** [comment]
strange, godef works quite well on my machine without renaming. 
but i'll keep this renaming.

**Pull request merged**
