### PR TITLE
Update build-release.sh

### PR DESCRIPTION
**Pull request by higher-sy**
change md5 to sha256
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xtaci/kcptun/pull/390%23issuecomment-277413139%22%2C%20%22https%3A//github.com/xtaci/kcptun/pull/390%23issuecomment-277419978%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xtaci/kcptun/pull/390%23issuecomment-277413139%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22mac%20doesn%27t%20have%20sha256sum%20only%20shasum%22%2C%20%22created_at%22%3A%20%222017-02-04T02%3A49%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2346725%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/xtaci%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20using%20%60hash%60%20to%20check%20sha1sum%20existence%20is%20simpler%2C%20is%20it%3F%22%2C%20%22created_at%22%3A%20%222017-02-04T05%3A14%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2346725%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/xtaci%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xtaci/kcptun/pull/390#issuecomment-277413139'>General Comment</a></b>
- <a href='https://github.com/xtaci'></a> mac doesn't have sha256sum only shasum
- <a href='https://github.com/xtaci'></a> I think using `hash` to check sha1sum existence is simpler, is it?

<a href='https://www.codereviewhub.com/xtaci/kcptun/pull/390?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xtaci/kcptun/pull/390?approve=1'></a>&nbsp;<a href='https://github.com/xtaci/kcptun/pull/390'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xtaci** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xtaci/kcptun/pull/390'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by xtaci** [comment]
mac doesn't have sha256sum only shasum

**Comment by xtaci** [comment]
I think using `hash` to check sha1sum existence is simpler, is it?

**Comment by xtaci** [comment]
merged!

**Comment by higher-sy** [comment]
See you in next release! 😃

**Pull request closed without merging**
