### PR TITLE
Log connecting ip

### PR DESCRIPTION
**Pull request by liaoxiaorong**
Someone like me have several client to connect kcp client, It would be help if log the connecting ip information.

the log will be like this:
```
2019/06/11 10:34:17 main.go:34: stream opened 3  from: 127.0.0.1:58944
2019/06/11 10:34:20 main.go:34: stream opened 5  from: 10.229.33.41:62574
2019/06/11 10:34:22 main.go:34: stream opened 15  from: 10.229.33.41:62590
2019/06/11 10:34:30 main.go:34: stream opened 19  from: 10.229.33.41:62598
2019/06/11 10:34:31 main.go:34: stream opened 21  from: 127.0.0.1:58946
2019/06/11 10:34:34 main.go:34: stream opened 25  from: 127.0.0.1:58950
```

### CODE REVIEW

**Comment by xtaci** [comment]
how about 'stream opened 127.0.0.1:58944(3)' or any thing that's not wordy

**Comment by liaoxiaorong** [comment]
OK, updated

```
2019/06/11 13:11:32 main.go:34: stream opened 127.0.0.1:59856(3)
2019/06/11 13:12:35 main.go:34: stream opened 10.229.33.41:63293(15)
2019/06/11 13:12:37 main.go:34: stream closed 10.229.33.41:63293(15)
```

**Comment by liaoxiaorong** [comment]
Oh, I see you already updated. So closed.

**Comment by liaoxiaorong** [comment]
Actually what you change will not work as you expected.
`p2.RemoteAddr()` will alway be nil.

**Comment by xtaci** [comment]
check the latest commit

**Comment by liaoxiaorong** [comment]
This is ok for me. Closed.

**Pull request closed without merging**
