### PR TITLE
add unix socket support on server side

### PR DESCRIPTION
**Pull request by maskedeken**

### CODE REVIEW

**Comment by xtaci** [comment]
Could you tell me under what circumstances this might be used?

**Comment by maskedeken** [comment]
> 
> 
> Could you tell me under what circumstances this might be used?

Some services like v2ray could serve as a unix socket, which is hiding the listening port on a censored system like AliCloud

**Comment by xtaci** [comment]
why not just listen on 127.0.0.1?

**Comment by maskedeken** [comment]
> 
> 
> why not just listen on 127.0.0.1?

besides, unix socket is faster than tcp socket.

UNIX domain sockets know that they’re executing on the same system, so they can avoid some checks and operations (like routing); which makes them faster and lighter than IP sockets. So if you plan to communicate with processes on the same host, this is a better option than IP sockets.

**Comment by xtaci** [comment]
how about re-try scheme? like:
```
var c conn
if c, err := net.Dial("tcp", xxx) err ==nil{
} else if c, err := net.Dial("unix", xxx);err==nil{
}
```
then we dont' have to specify `unix://`

**Comment by xtaci** [comment]
any comment?

**Comment by maskedeken** [comment]
> 
> 
> any comment?

I don't think that's a good idea. using try/catch as if/else is a bad practice.

**Comment by xtaci** [comment]
https://github.com/xtaci/kcptun/blob/master/server/main.go#L57-L66

**Comment by xtaci** [comment]
or, we can just try parse target to IP address and Port

**Comment by maskedeken** [comment]
> 
> 
> or, we can just try parse target to IP address and Port

if you don't like the unix:// prefix, error checking is the only way to dial the right conn

**Comment by xtaci** [comment]
```go
	// check if target is unix domain socket
	var isUnix bool
	if _, _, err := net.SplitHostPort(config.Target); err != nil {
		isUnix = true
	}
```

a simple check, though not strict

**Comment by maskedeken** [comment]
> 
> 
> ```go
> 	// check if target is unix domain socket
> 	var isUnix bool
> 	if _, _, err := net.SplitHostPort(config.Target); err != nil {
> 		isUnix = true
> 	}
> ```
> 
> a simple check, though not strict

Great

**Pull request closed without merging**
