### PR TITLE
Added github workflow for docker and dependabot

### PR DESCRIPTION
**Pull request by itspooya**

### CODE REVIEW

**Comment by xtaci** [comment]
what's this for?

**Comment by itspooya** [comment]
I've been a fan of this project. One thing I've noticed is that there isn't an official Docker image available, making it a bit more difficult to get started.
To address this, I've created this pull request to introduce a GitHub Actions workflow that automates the building of a Docker image for each tag and release. This means that with each new version, an updated Docker image will be automatically built and hosted on GitHub Container Registry (GHCR). This should make it easier for users to get started with the project and take advantage of the latest changes.
I hope this contribution helps to make the project more accessible and user-friendly!

**Comment by itspooya** [comment]
Hi
I wanted to check status of this PR
also as a sample you can check current forked repository in my repository list to see how it would work
@xtaci

**Comment by xtaci** [comment]
sorry for the delay, I was on a vacation.

**Comment by itspooya** [comment]
Hey, because current workflow is on release and on tag, I don't know when you want to release something new, I wanted to ask you please for now consider running docker workflow manually to have the docker images created or maybe you can release
https://github.com/xtaci/kcptun/actions/workflows/docker.yml

**Comment by itspooya** [comment]
> Hey, because current workflow is on release and on tag, I don't know when you want to release something new, I wanted to ask you please for now consider running docker workflow manually to have the docker images created or maybe you can release https://github.com/xtaci/kcptun/actions/workflows/docker.yml

@xtaci

**Comment by itspooya** [comment]
> https://github.com/xtaci/kcptun/actions/runs/9144409885 What else should I do?
https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package

**Pull request merged**
